/********************************************************************************
** Form generated from reading UI file 'plugin_formesPwsh.ui'
**
** Created by: Qt User Interface Compiler version 5.15.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef PLUGIN_FORMESPWSH_H
#define PLUGIN_FORMESPWSH_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>
#include "Qt/QmaxSpinBox.h"

QT_BEGIN_NAMESPACE

class Ui_PluginRollup
{
public:
    QVBoxLayout *verticalLayout;
    QLabel *label;
    QLabel *label_2;
    MaxSDK::QmaxSpinBox *spinBox;
    QPushButton *pushButton;

    void setupUi(QWidget *PluginRollup)
    {
        if (PluginRollup->objectName().isEmpty())
            PluginRollup->setObjectName(QString::fromUtf8("PluginRollup"));
        PluginRollup->resize(205, 181);
        QFont font;
        font.setFamily(QString::fromUtf8("MS Gothic"));
        PluginRollup->setFont(font);
        verticalLayout = new QVBoxLayout(PluginRollup);
        verticalLayout->setObjectName(QString::fromUtf8("verticalLayout"));
        label = new QLabel(PluginRollup);
        label->setObjectName(QString::fromUtf8("label"));
        label->setAlignment(Qt::AlignCenter);

        verticalLayout->addWidget(label);

        label_2 = new QLabel(PluginRollup);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setAlignment(Qt::AlignCenter);

        verticalLayout->addWidget(label_2);

        spinBox = new MaxSDK::QmaxSpinBox(PluginRollup);
        spinBox->setObjectName(QString::fromUtf8("spinBox"));

        verticalLayout->addWidget(spinBox);

        pushButton = new QPushButton(PluginRollup);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));

        verticalLayout->addWidget(pushButton);


        retranslateUi(PluginRollup);

        QMetaObject::connectSlotsByName(PluginRollup);
    } // setupUi

    void retranslateUi(QWidget *PluginRollup)
    {
        PluginRollup->setWindowTitle(QCoreApplication::translate("PluginRollup", "Form", nullptr));
        label->setText(QCoreApplication::translate("PluginRollup", "<html><head/><body><p>Generated by Autodesk 3ds Max</p><p>SDK Plug-in Wizard</p></body></html>", nullptr));
        label_2->setText(QCoreApplication::translate("PluginRollup", "<html><head/><body><p>TODO: Place panel</p><p>controls here.</p></body></html>", nullptr));
        pushButton->setText(QCoreApplication::translate("PluginRollup", "PushButton", nullptr));
    } // retranslateUi

};

namespace Ui {
    class PluginRollup: public Ui_PluginRollup {};
} // namespace Ui

QT_END_NAMESPACE

#endif // PLUGIN_FORMESPWSH_H
